### ISSUE TITLE
Assignments page shows wrong students

### ISSUE THREAD

**Issue by jamesdabbs** [jamesdabbs/ferrite#12]
![screen shot 2015-05-29 at 8 58 20 am](https://cloud.githubusercontent.com/assets/1079270/7882998/fe705b04-05e0-11e5-9b13-cce3deb5f56b.png)

**Comment by kwals** [comment]
Is it something to do with the policy scope for assignments? I had set it .index? to true to allow it to index the students, but the scope is still in active course.

**Comment by jamesdabbs** [comment]
Whoops. That's a misleading bug report. That's the course show page.

**Comment by kwals** [comment]
Has that instructor added students yet? (Trying to figure out if the course show page showing all students in the database, or showing the wrong group of students in the database.)

**Comment by kwals** [comment]
Changed the policy scope so that the Course show page only lists students in that course.
